name: .NET MVC Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Restore NuGet packages
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test --configuration Release

    - name: Publish
      run: dotnet publish --configuration Release --output ./publish

  deploy:
    needs: build
    runs-on: windows-latest

    steps:
    - name: Deploy to IIS
      uses: jexuswebapps/iis-web-app-deploy@v1.5
      with:
        publish-dir: ./publish
        website-name: 'MyWebApp'
        app-pool: 'MyAppPool'
        iis-instance: 'localhost'
